### ISSUE TITLE
Terminar o CRUD da API

### ISSUE THREAD

**Issue by Bumbleblo** [Alohomora-team/2019.2-Alohomora#1]
**Descreva a solução que gostaria**

A API ainda não tem todas as queries e mutations implementados (deletar models, atualizar, query, etc). Essa issue propõe criar essas estruturas de controle faltantes.

**Funcionalidades requeridas**

- [x] Criar query para busca das models
- [x] Criar mutation para criação das models
- [x] Criar mutation para atualização das models
- [x] Criar mutation para deletar as models
- [x] Alterar o CHANGELOG
- [x] Testes

**Comment by higton** [comment]
Tenho que esperar o PR #7  para poder dar um commit.

**Comment by higton** [comment]
Tentei aplicar um forma de atualização

```
class UpdateService(graphene.Mutation):
    user = graphene.Field(UserType)

    class Arguments:
        user_data = ServiceInput()

    @login_required
    def mutate(self, info, user_data=None):
        user = info.context.user
        if user.is_service is not True:
            raise Exception('User is not service')

        for k, v in user_data.items():
            if (k == 'password') and (v is not None):
                user.set_password(user_data.password)
            else:
                setattr(service, k, v)
        try:
            user.full_clean()
            user.save()
            return UpdateUser(user=user)

        except ValidationError as e:
            return UpdateUser(user=user, errors=e)
```
Mas pelo jeito só vai consegui atualizar o email e senha das models. Pois só consigo pegar o user base do django pela sessão e não a model.

**Comment by higton** [comment]
Agora está faltando terminar os testes e separar em arquivos diferentes o código.

**Comment by higton** [comment]
Para terminar esta issue está faltando, consertar o bug do update dos testes, deixar o lint com nota 10, separar em files diferentes os códigos dos schemas e dos testes. Fora isso, falta melhorar os testes unitários do update e colocar de volta as permissões.

**Comment by higton** [comment]
Consertei o bug do update dos blocks. Deletando as migrations e trocando o field da primary key. Preciso analisar direito qual foi a causa do bug.
