### ISSUE TITLE
Criar mecanismo de ativação dos usuários

### ISSUE THREAD

**Issue by Bumbleblo** [Alohomora-team/2019.2-Alohomora#2]
**Descreva a solução que gostaria**

No fluxo atual o morador realiza o cadastro e tem acesso ao sistema, porém a forma correta de implementar essa funcionalidade e fazendo com que o sindico permita que o usuário tenha acesso ao sistema. Essa tarefa é para implementar esse mecanismos e suas validações no banco de dados e API.

**Funcionalidades requeridas**

- [x] Fazer com que os usuários novos no banco não tenham acesso as queries até a permissão do administrador do sistema.
- [x] Criar Mutation para que o administrador do sistema consiga ativar um usuário
- [x] Aterar o CHANGELOG com as alterações feitas
- [x] Testes 

**Contexto Adicional**

Para desativar o usuário veja se a flag is_active do baseUser pode lhe ajudar.

**Comment by higton** [comment]
@AlineLermen como está o andamento da issue?

**Comment by higton** [comment]
Utilizando a flag is_active do django, e colocando false como padrão. O user não vai conseguir fazer o login até que o admin permita. Então vai ser necessário apenas colocar um resolver qualquer de autenticação antes de uma função, se quiser que não seja acessado pelo usuario desativado.
