### ISSUE TITLE
Adicionar mutation de feedback na aplicação

### ISSUE THREAD

**Issue by Bumbleblo** [Alohomora-team/2019.2-Alohomora#3]
**Descreva a solução que gostaria**

Disponibilizar uma forma com que as pessoas possam dar feedbacks sobre o sistema.

**Funcionalidades requeridas**

- [x] Criar model de feedback no banco
- [x] Criar mutation para cadastrar os feedbacks
- [x] Alterar arquivo CHANGELOG adicionando alterações feitas
- [ ] testes

**Comment by luis-furtado** [comment]
* Criei um PR na Branch `3_mutation_feedback_aplicacao` com a nova funcionalidade.

* Falta a implementação dos testes

**Comment by higton** [comment]
@baraky e @luis-furtado voces estão com alguma dificuldade para fazer os testes?
