### ISSUE TITLE
Adicionar fixtures para models da API

### ISSUE THREAD

**Issue by Bumbleblo** [Alohomora-team/2019.2-Alohomora#4]
**Descreva a solução que gostaria**

Adicionar um arquivo de fixture para cada model da API para que as mesmas sejam usadas em desenvolvimento. A model do administrador deve ter um nome padrão e senha padrão para que seja usado como primeiro administrador do projeto.

**Funcionalidades requeridas**

-  [x] Criar uma fixture (dump) para cada model do projeto (deixe o arquivo no mesmo app onde esta localizado a model).
- [x] Criar comando no django para fazer load de todas as fixtures 
- [x] Adicionar entradas no CHANGELOG

**Contexto Adicional**

* [Documentação do django fixture](https://docs.djangoproject.com/pt-br/2.2/howto/initial-data/)
* [Exemplo de comando no django para rodar as fixtures](https://django-testing-docs.readthedocs.io/en/latest/fixtures.html)

**Comment by AlineLermen** [comment]
Criei uma fixture para as models Block e Apartment de "condos".

Falta ainda as models de "accounts". Acredito que seja melhor esperar a revisão do PR #7 para prosseguir com essas fixtures, pois há alteração nas models.

Estou com uma dúvida em relação à segunda funcionalidade requerida. Onde deve ser inserido o comando para fazer load de todas as fixtures? Por enquanto, pra verificar se estava funcionando, utilizei o comando no terminal apenas.
