### ISSUE TITLE
Adicionar registros de entrada do morador

### ISSUE THREAD

**Issue by Bumbleblo** [Alohomora-team/2019.2-Alohomora#6]
**Descreva a solução que gostaria**

Salvar no banco de dados as informações de entrada do morador.

**Funcionalidades requeridas**

- [ ] Criar tabela com essa informação no banco
- [ ] Criar mutation na API
- [ ] Adicionar entradas no CHANGELOG
- [ ] test

**Contexto Adicional**
Adicionem outros contextos e fotos das telas

**Comment by baraky** [comment]
Enquanto eu dava uma lida na documentação do Django pra melhorar meu entendimento sobre, vi algo que pode ajudar no desenvolvimento dessa issue. Trata-se de um meio de intermediar uma relação many-to-many e acredito que encaixa muito bem na solução.

A ideia é uma model que faz a conexão entre as duas outras models (Visitor e Apartment (?)), como a [documentação](https://docs.djangoproject.com/en/2.2/topics/db/models/#extra-fields-on-many-to-many-relationships) exemplifica bem.

**Comment by higton** [comment]
@luis-furtado como está o andamento da issue?

**Comment by luis-furtado** [comment]
@higton estava ocupado resolvendo as outras issues que fui designado essa semana. Hoje começarei essa. Você ficará pela parte dos testes ?

**Comment by luis-furtado** [comment]
Ok @higton, enquanto isso vou começando aqui a issue para ir nos adiantando.

**Comment by luis-furtado** [comment]
@higton consegui fazer a model Entry com sua respectiva query e mutation (testei a funcionalidade e está ok). Irei abrir um PR e linkar nessa issue e podemos prosseguir com o que falta.

O que falta:

* Criar query com argumento para filtro de entries
* Testes

**Comment by higton** [comment]
Muito bom @luis-furtado a parte mais difícil você já fez.
